all:
	g++ server_round_trip.cpp -o server_round_trip
	g++ client_round_trip.cpp -o client_round_trip
	g++ server_bandwidth.cpp -o server_bandwidth
	g++ client_bandwidth.cpp -o client_bandwidth
	g++ client_connection_overhead.cpp -o client_connection_overhead

clean:
	rm -rf *o server_round_trip
	rm -rf* server_round_trip
	rm -rf* client_round_trip
	rm -rf* server_bandwidth
	rm -rf* client_bandwidth
	rm -rf* client_connection_overhead